### ISSUE TITLE
ELK has all been up, logspout run through the docker run

### ISSUE THREAD

**Issue by huyifanstar** [Bekt/logspout-logstash#3]
docker run -d   bekt/logspout-logstash  -e ROUTE_URIS: logstash://ip:5000  -v /var/run/docker.sock:/var/run/docker.sock

```
root@docker:~# docker  logs  714959c7b1c7
# logspout v3.2-dev-custom by gliderlabs
# adapters: tcp logstash raw udp
# options : persist:/mnt/routes
!! bad adapter: 
```

What should I do ?

**Comment by Bekt** [comment]
Is `logstash://ip:5000` accessible from inside of the container?

**Comment by huyifanstar** [comment]
Logstash 5000 port is not running, github provided in the compose not open 5000 port ah ！
docker compose:
logstash:
    image:  elkstack/logstash-logspout
    restart: unless-stopped
    command: -f /opt/logstash/sample.conf

**Comment by huyifanstar** [comment]
No ports parameter  ,This?
logstash:
image: elkstack/logstash-logspout
ports:
  5000:5000
restart: unless-stopped
command: -f /opt/logstash/sample.conf

**Comment by huyifanstar** [comment]
logstash:
    image: elkstack/logstash-logspout
    ports:
      - 5000:5000/udp
    restart: unless-stopped
    command: -f /opt/logstash/sample.conf



root@vm10-140-92-130:~# nc -w2  -u  10.140.31.128   5000
root@vm10-140-92-130:~# echo $?
0
root@vm10-140-92-130:~
docker run -d   bekt/logspout-logstash  -e ROUTE_URIS: logstash://10.140.31.128:5000/udp  -v /var/run/docker.sock:/var/run/docker.sock

root@vm10-140-92-130:~# docker  logs 4544785d3fd2
# logspout v3.2-dev-custom by gliderlabs
# adapters: udp tcp logstash raw
# options : persist:/mnt/routes
!! bad adapter: 
root@vm10-140-92-130:~# 


Port normal, how should I do?

**Comment by huyifanstar** [comment]
@Bekt   Please help me, thank you！

**Comment by Bekt** [comment]
Can you post your full docker-compose file? From the snippet above, it looks like you didn't mount the `/opt/logstash/sample.conf` file in logstash.

**Comment by huyifanstar** [comment]
The sample.conf file is in the mirror

**Comment by Bekt** [comment]
Can you give me a docker-compose file I can run? Otherwise I have no idea with the given information.

**Comment by huyifanstar** [comment]
Customized mirrors.
Mirror problem should not, and now logspout use compose, logspout with logstash use is no problem, it should not be a component of the problem. Now I have multiple logspout need to run in different nodes, can not use compose to run it

**Comment by huyifanstar** [comment]
Is there more than one instance of the same service name that is also supported in version 0.1.0?
RC1 Do you have an address ？

**Comment by huyifanstar** [comment]
version: '2'
services:
  elasticsearch:
    image: 10.140.92.130:8050/elkstack/elasticsearch
    restart: unless-stopped
    ports:
    - 9200:9200
  kibana:
    image: 10.140.92.130:8050/elkstack/kibana:latest
    restart: unless-stopped
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
    - 5601:5601
  logstash:
    image: 10.140.92.130:8050/elkstack/logstash-logspout
    ports:
    - 5000/udp:5000/udp
    restart: unless-stopped
    command: -f /opt/logstash/sample.conf
  redis:
    image: redis
    restart: unless-stopped

**Comment by Bekt** [comment]
Hey @huyifanstar, were you able to figure out?
